image: python:2.7

pipelines:
  default:
    - step:
        script:
          - pip install pep8
          - pep8 nessus tests
          - pip install -r requirements.txt
          - pip install j2cli
          - j2 nessus.ini.example > nessus.ini
          - pytest
