image: codeparticle/docker-tox

pipelines:
  default:
    - step:
        script:
          - pip install pep8
          - pep8 nessus tests
          - pip install j2cli
          - j2 nessus.ini.example > nessus.ini
          - tox
